### Understand Simple Neural Network arch

In [38]:
#imports!
import tensorflow as tf
import numpy as np
import os,sys
from IPython.display import Image

### Visualize Neural Nets
<img src="imgs/nn.png">

#### An example to show how tf.multiply does element wise multiplication 

In [39]:
with tf.Graph().as_default() as graph:
    x = tf.ones((3,4),name='x',dtype=tf.int32)
    y_= tf.convert_to_tensor(np.array(((2,2,2))).reshape(3,1),name="y",dtype=tf.int32)
    y = tf.convert_to_tensor(np.array(((2,2,2),(3,4,5),(4,5,3),(3,3,3))).reshape(3,4),name="y",dtype=tf.int32)
    mul = tf.multiply(x,y,name='mul')
    mul_ = tf.multiply(x,y_,name='mul')

    with tf.Session() as sess:
        print "tf.multiply without broadcasting"
        print sess.run(mul)
        print "\n"
        print "tf.multiply with broadcasting"
        print sess.run(mul_)

[[2 2 2 3]
 [4 5 4 5]
 [3 3 3 3]]


[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [42]:
with tf.Graph().as_default() as graph:
    
    #inputs from input layer,which is just 3 values
    x = tf.convert_to_tensor(np.random.normal(size = (3,1))) 
    #or
    x = tf.random_normal((3,1),name="x")
    
    '''
    weights are of shape (3,4) because there are three features for each 
    sample/example and each feature needs to connect with 4 neurons in hidden
    layer_1
    '''
    w1 = tf.convert_to_tensor(np.random.normal(size=(3,4)))
    #or
    w1 = tf.random_normal((3,4),name="w1")
    
    #hidden layer, where we get both z = wT*x and a = sigmoid(z)
    hl1 = tf.reduce_sum(tf.multiply(w1,x),name="hl1")
    b1 = tf.ones((w1.shape[1],1),name="b1")
    a1 = tf.sigmoid(hl1+b1,name="a1")
    
    '''
    weights between hidden layer and output layer is of shape(4,2), since there
    are 4 inputs and two outputs
    '''
    w2 = tf.random_normal((4,2),name="w2")
    
    #output layer
    ol = tf.reduce_sum(tf.multiply(w2,a1),name="ol")
    b2 = tf.ones((w2.shape[1],1),name="b2")
    a2 = tf.sigmoid(ol+b2,name="output")
    
    with tf.Session(graph=graph) as sess:
        writer = tf.summary.FileWriter("./graphs",graph=sess.graph)
        sess.run(a1)
        writer.close()
os.system("tensorboard --logdir="+"./graphs")
        


2

In [53]:
a = tf.constant(2,name = "a")
b = tf.constant(3,name = "b")
c = tf.add(a,b,name="add")
with tf.Session() as sess:
    writer = tf.summary.FileWriter("./graphs",graph=sess.graph)
    sess.run(c)
    writer.close()
os.system("tensorboard --logdir="+"./graphs")

2